<?php


namespace App\App;


use App\Models\Database\AppDatabase;
use System\App\AppLogger;
use System\Updater;

class AppUpdater extends Updater
{
    public function __construct()
    {
        $this->user = App::get()->user;
        $tmp = ROOTPATH . DIRECTORY_SEPARATOR . "writable" . DIRECTORY_SEPARATOR . "core_update";
        $dst = ROOTPATH;
        parent::__construct('https://raw.githubusercontent.com/jacobsen9026/AD-Accounts-Manager/master/update/update.json', $tmp, $dst, App::$version);
        $this->logger->info("Creating updater");
        $this->setCheckSSL(false);
    }


    /**
     * @inheritDoc
     */
    public function getLatestVersionsFromURL()
    {
        $return = parent::getLatestVersionsFromURL(); // TODO: Change the autogenerated stub
        /**
         * Update the database last update check time
         */
        AppDatabase::setLastUpdateCheck(time());
        /**
         * Update the database latest version
         */
        AppDatabase::setLatestAvailableVersion(json_encode([$this->latestVersion, $this->latestVersionURL]));
        return $return;
    }

    public function getSimulationResults()
    {
        return $this->updater->getSimulationResults();
    }


}